README.md
The glibc* packages are now signed and no longer require the use of
the --allow-untrusted flag to apk.  This updates the README to show how
to install Andy's key to ensure the downloaded packages are signed.
=> Update README for signed packages

APKBUILD
💁  An invalid SSH public key has been included in previous releases. Releasing a new version of this package should give downstream consumers more confidence.
=> Bump release version to 2.23-r3

APKBUILD
💁  This change updates the maintainer details in the project's build file, which was missed in 3db7b4c4729f8128df99c9007a56a8f0d1e65955.
=> Update maintainer details

APKBUILD, README.md
💁  Releases version 2.24 of the glibc package.
=> Bump glibc version to v2.24

APKBUILD, README.md
💁  These changes bump the version of glibc to 2.25.
Closes #35
=> Bump upstream glibc version to v2.25

APKBUILD
💁  These changes add a `glibc-dev` package.
Closes #43
=> Create -dev subpackage

circle.yml
💁 These changes update the build definition to reference version 3.6 of Alpine Linux, as well as account for some configuration related changes that occurred in the build image.
=> Update build image references

APKBUILD
💁  These changes release version 2.24 of the glibc package.
=> Update glibc version to 2.26

README.md
💁 I missed updating the installation documentation in #64. This change corrects that.
=> Reference 2.26 installation docs

APKBUILD, README.md
💁  Releases version 2.27 of the [glibc](https://www.gnu.org/software/libc/) package.
=> Bump glibc version to 2.27

APKBUILD, README.md
💁 Releases version 2.28 of the [glibc](https://www.gnu.org/software/libc/) package.
=> glibc v2.28

APKBUILD
💁 The upstream GNU libc project uses LGPL for the library component of glibc. Updated the package's license to reflect this, as well as copying in the relevant project license files.
Closes #61.
=> Change package license to LGPL

.circleci/config.yml, APKBUILD, README.md
💁 Releases [version 2.29](https://sourceware.org/ml/libc-announce/2019/msg00000.html) of the [GNU C Library](https://www.gnu.org/software/libc/) package.
Closes #105
=> glibc v2.29

APKBUILD
💁 Resolves the existing issue:
```
fetch http://dl-cdn.alpinelinux.org/alpine/v3.9/main/x86_64/APKINDEX.tar.gz
fetch http://dl-cdn.alpinelinux.org/alpine/v3.9/community/x86_64/APKINDEX.tar.gz
(1/5) Installing ncurses-terminfo-base (6.1_p20190105-r0)
(2/5) Installing ncurses-terminfo (6.1_p20190105-r0)
(3/5) Installing ncurses-libs (6.1_p20190105-r0)
(4/5) Installing readline (7.0.003-r1)
(5/5) Installing bash (4.4.19-r1)
Executing bash-4.4.19-r1.post-install
Executing busybox-1.29.3-r10.trigger
Executing glibc-bin-2.29-r0.trigger
OK: 21 MiB in 22 packages
/ # /usr/glibc-compat/bin/ldd /bin/ls
linux-vdso.so.1 (0x00007ffd09cf9000)
libc.musl-x86_64.so.1 => /lib/libc.musl-x86_64.so.1 (0x00007f78b3545000)
```
Fixes #103.
=> Symlink lib64 version of Linux image file

README.md
I believe there is a minor typo in the readme, since the binary's name is actually `localedef` and not `localdef`.
=> Fix typo: localdef -> localedef

APKBUILD, README.md
💁 Releases [version 2.30](https://sourceware.org/ml/libc-alpha/2019-08/msg00029.html) of the [GNU C Library](https://www.gnu.org/software/libc/) package.
=> glibc v2.30

.circleci/config.yml
💁 Alpine Linux 3.11 was [released on 2019-12-19](https://alpinelinux.org/posts/Alpine-3.11.0-released.html) and should be used as part of the build and test jobs.
=> Alpine Linux 3.11

APKBUILD
💁 These changes release [version 2.31](https://sourceware.org/ml/libc-announce/2020/msg00001.html) of the [GNU C Library](https://www.gnu.org/software/libc/) package.
Closes #132
=> glibc 2.31

APKBUILD
💁 These changes release [version 2.32](https://sourceware.org/pipermail/libc-announce/2020/000029.html) of the [GNU C Library](https://www.gnu.org/software/libc/) package.
Closes #137
=> Update glibc to 3.12

README.md
💁 Related to #141 and needed before tagging this release.
Unfortunately the doctests have a 🐔 and 🥚 problem, in that they will fail on this branch until `2.32-r0` is tagged. I'll re-run them after that.
=> Update documentation to reference v2.32

APKBUILD, README.md
💁 These changes release [version 2.33](https://sourceware.org/pipermail/libc-announce/2021/000030.html) of the [GNU C Library](https://www.gnu.org/software/libc/) package.
Closes #149
=> Update glibc to v2.33

APKBUILD, README.md
💁 These changes release [version 2.34](http://sourceware.org/pipermail/libc-announce/2021/000032.html) of the [GNU C Library](https://www.gnu.org/software/libc/) package.
Closes #162
=> Update glibc to v2.34

.circleci/config.yml, APKBUILD
💁 These changes release [version 2.35](https://sourceware.org/pipermail/libc-alpha/2022-February/136040.html) of the [GNU C Library](https://www.gnu.org/software/libc/) package.
Closes #170
=> Update glibc to v2.35

README.md
💁 I changed the default branch name some time ago but had neglected to update the documentation at the same time.
=> Update branch name in CircleCI badge
